### ISSUE TITLE
Unable to understand how to make eclipselsp lint java files

### ISSUE THREAD

**Issue by Adityashaw** [dense-analysis/ale#3132]
I have installed jdtls from aur ( [link to it](https://aur.archlinux.org/packages/jdtls/) ).
I have following lines related to ale in my `.vimrc`
```

let g:ale_completion_enabled = 1
" vimrc.plug is sourced after this

" Allow Italics in spacegray
let g:spacegray_use_italics = 1

" ALE Lint on text changed
let g:ale_lint_on_text_changed = 1

" ALE Lint should delay a bit
let g:ale_lint_delay = 2000

" Let ALE know to what Linter to use for various programming languages
let g:ale_linters = {'javascript': ['eslint'],
                    \ 'java': ['eclipselsp']
                    \ }
" 'python':['pylint']

"Path to Eclipse LSP for ALE
let g:ale_java_eclipselsp_path = '/usr/share/java/jdtls'
let g:ale_java_eclipselsp_executable = '/usr/bin/jdtls'
let g:ale_java_eclipselsp_config_path = '$HOME/.jdtls'

" Show errors on Statusline
let g:airline#extensions#ale#enabled = 1

" Use Quickfix List instead of LocList
"let g:ale_set_loclist = 0
"let g:ale_set_quickfix = 1
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 1
let g:ale_list_window_size = 5
```
`ls /usr/share/java/jdtls/` shows
```
config_linux  config_ss_linux  config_ss_win  features
config_mac    config_ss_mac    config_win     plugins
```
`$HOME/.jdtls` is an **empty** directory created by me. I thought this might be needed.

If I simply open any _.java_ file, nothing happens. And type `:ALEInfo` then `Command History:` is empty. If I add an empty `build.gradle` file then I see the following line in `:ALEInfo`
```                                                                      
(executable check - success) /usr/bin/jdtls                                                 
(started) ['/bin/bash', '-c', '''/usr/bin/jdtls'' -version']    
```
but no linting whatsoever.
Full :ALEInfo 
```

 Current Filetype: java
Available Linters: ['checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd']
  Enabled Linters: ['eclipselsp']
 Suggested Fixers: 
  'google_java_format' - Fix Java files with google-java-format.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'uncrustify' - Fix C, C++, C#, ObjectiveC, ObjectiveC++, D, Java, Pawn, and VALA files with uncrustify.
 Linter Variables:

let g:ale_java_eclipselsp_config_path = '$HOME/.jdtls'
let g:ale_java_eclipselsp_executable = '/usr/bin/jdtls'
let g:ale_java_eclipselsp_path = '/usr/share/java/jdtls'
let g:ale_java_eclipselsp_workspace_path = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 1
let g:ale_lint_delay = 2000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 1
let g:ale_linter_aliases = {}
let g:ale_linters = {'java': ['eclipselsp'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = 5
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 1
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /usr/bin/jdtls
(started) ['/bin/bash', '-c', '''/usr/bin/jdtls'' -version']
```
[My Full .vimrc](https://gist.github.com/Adityashaw/8ac76b0a7ab22601a831bdef4dbb126a) 
_How to make ALE lint my Java Files?_

**Comment by Adityashaw** [comment]
I found on your Doc that `let g:ale_java_eclipselsp_executable` should point to Java Executable.
So I commented it out it in `.vimrc`.
Now, 
> If I simply open any .java file, nothing happens. And type :ALEInfo then `Command History:` is empty. If I add an empty build.gradle file then I see the following line in :ALEInfo
>
>(executable check - success) /usr/bin/jdtls                                                 
>(started) ['/bin/bash', '-c', '''/usr/bin/jdtls'' -version']    

this changes to 
```
  Command History:                                                                          
(executable check - success) java                                                           
(finished - exit code 0) ['/bin/bash', '-c', '''java'' -version']                           
<<<NO OUTPUT RETURNED>>>                                                                    
(finished - exit code 0) ['/bin/bash', '-c', '''java'' -version']                           
<<<NO OUTPUT RETURNED>>>                                                                    
(finished - exit code 0) ['/bin/bash', '-c', '''java'' -version']                           
<<<NO OUTPUT RETURNED>>>  
```
Still, no linting.

**Comment by Adityashaw** [comment]
I couldn't make this **jtdls** installed via package manager work.
I have built it from GitHub Repo. If you do not support the system wide installation then please close this issue.
Thank you!

**Comment by hsanson** [comment]
@Adityashaw found some issues with how ALE detects the eclipselsp jar file and java version. This PR #3137 should fix these and hopefully get it working for you.  Note that ALE does not show any progress status for language servers and it may take some time, depending on project size, to get any linter info back from eclipselsp.

I have not tested the system jtdls installation but support for it was added in #2523.

**Comment by hackingcat** [comment]
@hsanson I also install jdtls by aur . 
```
let g:ale_java_eclipselsp_executable = '/usr/bin/jdtls'
```
After choosing your PR #3137 , the eclipselsp command function is still not available.

**Comment by cogig** [comment]
@hackingcat @Adityashaw You can switch to [coc-java](https://github.com/neoclide/coc-java).Indeed, [coc.nvim](https://github.com/neoclide/coc.nvim) has better performance for language server protocol . Coc.nvim has a higher frequency of updates than ale.vim.

**Comment by hsanson** [comment]
@hackingcat is difficult for me to support jdtls since it does not exists in KDE neon that is my main distribution. Would be great if you can provide some more information for me to identify the issue.   Also I recommend you try the java-lsp that is the one I use daily for work.

If you are using vim (not neovim) can you enable language server debugging by adding this to your vimrc file:

```
call ch_logfile(expand('/tmp/chlogfile.log'), 'w')
````

Then open a java file and provide the outputs of ALEInfo and that chlogfile.log file to see what exactly is happening.

Also note that ALE only works on java projects, not individual files. To see if ALE is detecting a project open a Java file within a project and run this command:

```
:echo ale#java#FindProjectRoot('%')
```

If it outputs the root path of the java project then it is detecting the project.

**Comment by Adityashaw** [comment]
> @hackingcat @Adityashaw You can switch to [coc-java](https://github.com/neoclide/coc-java).Indeed, [coc.nvim](https://github.com/neoclide/coc.nvim) has better performance for language server protocol . Coc.nvim also has a higher frequency of updates than ale.vim.

Coc is highly problematic for most part. Needs a lot of configuration. I have tried that. I would better be without linting than using coc ever again.

**Comment by hsanson** [comment]
Added some instructions in the Wiki:  https://github.com/dense-analysis/ale/wiki/Java#eclipse-jdt
These have been proven to work: https://github.com/hsanson/vim-android/issues/111#issuecomment-1217397198
