### ISSUE TITLE
New Feature g:ale_hover_cursor Does Not Truncate Messages For Non-TSServer Language Servers

### ISSUE THREAD

**Issue by chengzeyi** [dense-analysis/ale#3266]
## Information

**VIM version**

VIM 8.1

Operating System: MACOS 10.15

## What went wrong

The new added feature `g:ale_hover_cursor` does not truncate the message for non-TSServer servers. ALE would always echo untruncated messages when the `CursorHoldI` event gets fired, which is extremely annoying and eventually makes the plugin `ALE` unusable. Hopping for a quickfix soon!

## Reproducing the bug

Digging into the source code, I found you only check the option `truncated_echo` for TSServer instead of all other language servers.

**Comment by w0rp** [comment]
I have pushed a fix for that now. Let me know if you have any issues.

**Comment by chengzeyi** [comment]
Still buggy here, got `Key not present in Dictionary: body.displayString`.
I think you should use `l:str` instead of `a:response.body.displayString`.

**Comment by w0rp** [comment]
Done. Try again.

**Comment by amadeus** [comment]
Not sure this is the right place for this - but I am seeing this error on occasion using Typescript Language server:

![image](https://user-images.githubusercontent.com/83376/91101237-83534780-e61b-11ea-9046-6d0fd7d55353.png)

I can't figure out how to reliably reproduce it - just seems to happen often - usually when I attempt to make a visual selection

**Comment by w0rp** [comment]
@amadeus I have pushed a commit now to catch E481 and just do nothing, if that ever happens.
